-- =====================================================
-- V001__CRIAR_FUNCOES_AUDITORIA.SQL
-- DESCRIÇÃO: FUNÇÕES E TRIGGERS PARA AUDITORIA AUTOMÁTICA
-- AUTOR: BRENO OLIVERA ALVES
-- DATA: 2025-01-10
-- =====================================================

-- =====================================================
-- EXTENSION PARA UUID (CASO PRECISE NO FUTURO)
-- =====================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- FUNÇÃO: ATUALIZAR TIMESTAMP DE ATUALIZAÇÃO AUTOMATICAMENTE
-- =====================================================
CREATE OR REPLACE FUNCTION ATUALIZAR_TIMESTAMP_ATUALIZACAO()
RETURNS TRIGGER AS $$
BEGIN
    NEW.ATUALIZADO_EM = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION ATUALIZAR_TIMESTAMP_ATUALIZACAO() IS
'TRIGGER FUNCTION QUE ATUALIZA AUTOMATICAMENTE O CAMPO ATUALIZADO_EM';

-- =====================================================
-- FUNÇÃO: VALIDAR CNPJ (FORMATO BÁSICO)
-- =====================================================
CREATE OR REPLACE FUNCTION VALIDAR_FORMATO_CNPJ(CNPJ_INPUT VARCHAR)
RETURNS BOOLEAN AS $$
BEGIN
    -- REMOVE CARACTERES NÃO NUMÉRICOS
    CNPJ_INPUT := REGEXP_REPLACE(CNPJ_INPUT, '[^0-9]', '', 'G');

    -- VERIFICA SE TEM 14 DÍGITOS
    IF LENGTH(CNPJ_INPUT) != 14 THEN
        RETURN FALSE;
END IF;

    -- VERIFICA SE NÃO SÃO TODOS DÍGITOS IGUAIS
    IF CNPJ_INPUT ~ '^(\D)\1{13}$' THEN
        RETURN FALSE;
END IF;

RETURN TRUE;
END;
$$ LANGUAGE PLPGSQL IMMUTABLE;

COMMENT ON FUNCTION VALIDAR_FORMATO_CNPJ(VARCHAR) IS
'VALIDA O FORMATO BÁSICO DE UM CNPJ (14 DÍGITOS, NÃO TODOS IGUAIS)';

-- =====================================================
-- FUNÇÃO: FORMATAR CNPJ (ADICIONAR PONTUAÇÃO)
-- =====================================================
CREATE OR REPLACE FUNCTION FORMATAR_CNPJ(CNPJ_INPUT VARCHAR)
RETURNS VARCHAR AS $$
DECLARE
CNPJ_LIMPO VARCHAR;
BEGIN
    -- REMOVE CARACTERES NÃO NUMÉRICOS
    CNPJ_LIMPO := REGEXP_REPLACE(CNPJ_INPUT, '[^0-9]', '', 'G');

    -- SE NÃO TIVER 14 DÍGITOS, RETORNA COMO ESTÁ
    IF LENGTH(CNPJ_LIMPO) != 14 THEN
        RETURN CNPJ_INPUT;
END IF;

    -- FORMATA: 00.000.000/0000-00
RETURN SUBSTRING(CNPJ_LIMPO, 1, 2) || '.' ||
       SUBSTRING(CNPJ_LIMPO, 3, 3) || '.' ||
       SUBSTRING(CNPJ_LIMPO, 6, 3) || '/' ||
       SUBSTRING(CNPJ_LIMPO, 9, 4) || '-' ||
       SUBSTRING(CNPJ_LIMPO, 13, 2);
END;
$$ LANGUAGE PLPGSQL IMMUTABLE;

COMMENT ON FUNCTION FORMATAR_CNPJ(VARCHAR) IS
'FORMATA CNPJ NO PADRÃO 00.000.000/0000-00';

-- =====================================================
-- FUNÇÃO: GERAR NÚMERO SEQUENCIAL (FORMATO CUSTOMIZADO)
-- =====================================================
CREATE OR REPLACE FUNCTION GERAR_NUMERO_SEQUENCIAL(
    PREFIXO VARCHAR,
    SEQUENCE_NAME VARCHAR,
    TAMANHO_NUMERO INTEGER DEFAULT 6
)
RETURNS VARCHAR AS $$
DECLARE
ANO_ATUAL VARCHAR(4);
    PROXIMO_NUMERO BIGINT;
    NUMERO_FORMATADO VARCHAR;
BEGIN
    -- PEGA O ANO ATUAL
    ANO_ATUAL := EXTRACT(YEAR FROM CURRENT_DATE)::VARCHAR;

    -- PEGA O PRÓXIMO VALOR DA SEQUENCE
EXECUTE FORMAT('SELECT NEXTVAL(%L)', SEQUENCE_NAME) INTO PROXIMO_NUMERO;

-- FORMATA O NÚMERO COM ZEROS À ESQUERDA
NUMERO_FORMATADO := LPAD(PROXIMO_NUMERO::VARCHAR, TAMANHO_NUMERO, '0');

    -- RETORNA NO FORMATO: PREFIXO-ANO-NUMERO
    -- EXEMPLO: CT-2025-000001
RETURN PREFIXO || '-' || ANO_ATUAL || '-' || NUMERO_FORMATADO;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION GERAR_NUMERO_SEQUENCIAL(VARCHAR, VARCHAR, INTEGER) IS
'GERA NÚMEROS SEQUENCIAIS NO FORMATO PREFIXO-ANO-NUMERO (EX: CT-2025-000001)';

-- =====================================================
-- FUNÇÃO: CALCULAR DATA LIMITE COM SLA (APENAS HORAS ÚTEIS)
-- CONSIDERA: SEG-SEX, 8H-18H, SEM FERIADOS
-- =====================================================
CREATE OR REPLACE FUNCTION CALCULAR_DATA_LIMITE_SLA(
    DATA_INICIO TIMESTAMP,
    SLA_HORAS INTEGER
)
RETURNS TIMESTAMP AS $$
DECLARE
DATA_ATUAL TIMESTAMP;
    HORAS_RESTANTES INTEGER;
    DIA_SEMANA INTEGER;
BEGIN
    DATA_ATUAL := DATA_INICIO;
    HORAS_RESTANTES := SLA_HORAS;

    -- SE SLA É 0 OU NEGATIVO, RETORNA DATA_INICIO
    IF SLA_HORAS <= 0 THEN
        RETURN DATA_INICIO;
END IF;

    WHILE HORAS_RESTANTES > 0 LOOP
        -- AVANÇA 1 HORA
        DATA_ATUAL := DATA_ATUAL + INTERVAL '1 HOUR';

        -- PEGA O DIA DA SEMANA (0=DOMINGO, 6=SÁBADO)
        DIA_SEMANA := EXTRACT(DOW FROM DATA_ATUAL);

        -- SE FOR DIA ÚTIL (SEG-SEX) E HORÁRIO COMERCIAL (8H-18H)
        IF DIA_SEMANA BETWEEN 1 AND 5 AND
           EXTRACT(HOUR FROM DATA_ATUAL) BETWEEN 8 AND 17 THEN
            HORAS_RESTANTES := HORAS_RESTANTES - 1;
END IF;
END LOOP;

RETURN DATA_ATUAL;
END;
$$ LANGUAGE PLPGSQL IMMUTABLE;

COMMENT ON FUNCTION CALCULAR_DATA_LIMITE_SLA(TIMESTAMP, INTEGER) IS
'CALCULA DATA LIMITE CONSIDERANDO APENAS HORAS ÚTEIS (SEG-SEX, 8H-18H)';

-- =====================================================
-- FUNÇÃO: LOG DE AUDITORIA COMPLETO (ARMAZENA JSON)
-- =====================================================
CREATE OR REPLACE FUNCTION REGISTRAR_AUDITORIA()
RETURNS TRIGGER AS $$
DECLARE
CODIGO_USUARIO_ATUAL BIGINT;
BEGIN
    -- TENTA PEGAR O CÓDIGO DO USUÁRIO DA SESSÃO
    -- (SERÁ SETADO PELO BACKEND VIA SET LOCAL)
BEGIN
        CODIGO_USUARIO_ATUAL := CURRENT_SETTING('APP.CODIGO_USUARIO', TRUE)::BIGINT;
EXCEPTION WHEN OTHERS THEN
        CODIGO_USUARIO_ATUAL := NULL;
END;

    -- INSERT
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO AUDITORIA (
            TABELA_AUDITADA,
            CODIGO_REGISTRO,
            OPERACAO,
            CODIGO_USUARIO,
            DATA_HORA_OPERACAO,
            DADOS_ANTERIORES,
            DADOS_NOVOS
        ) VALUES (
            TG_TABLE_NAME,
            (NEW.CODIGO_CLIENTE)::BIGINT,  -- AJUSTAR CONFORME A PK DA TABELA
            'INSERT',
            CODIGO_USUARIO_ATUAL,
            CURRENT_TIMESTAMP,
            NULL,
            ROW_TO_JSON(NEW)
        );
RETURN NEW;

-- UPDATE
ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO AUDITORIA (
            TABELA_AUDITADA,
            CODIGO_REGISTRO,
            OPERACAO,
            CODIGO_USUARIO,
            DATA_HORA_OPERACAO,
            DADOS_ANTERIORES,
            DADOS_NOVOS
        ) VALUES (
            TG_TABLE_NAME,
            (NEW.CODIGO_CLIENTE)::BIGINT,
            'UPDATE',
            CODIGO_USUARIO_ATUAL,
            CURRENT_TIMESTAMP,
            ROW_TO_JSON(OLD),
            ROW_TO_JSON(NEW)
        );
RETURN NEW;

-- DELETE
ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO AUDITORIA (
            TABELA_AUDITADA,
            CODIGO_REGISTRO,
            OPERACAO,
            CODIGO_USUARIO,
            DATA_HORA_OPERACAO,
            DADOS_ANTERIORES,
            DADOS_NOVOS
        ) VALUES (
            TG_TABLE_NAME,
            (OLD.CODIGO_CLIENTE)::BIGINT,
            'DELETE',
            CODIGO_USUARIO_ATUAL,
            CURRENT_TIMESTAMP,
            ROW_TO_JSON(OLD),
            NULL
        );
RETURN OLD;
END IF;

RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION REGISTRAR_AUDITORIA() IS
'REGISTRA TODAS AS OPERAÇÕES (INSERT, UPDATE, DELETE) NA TABELA DE AUDITORIA COM DADOS EM JSON';

-- =====================================================
-- TABELA: AUDITORIA GLOBAL (CRIADA AQUI PARA USO NAS TRIGGERS)
-- =====================================================
CREATE TABLE IF NOT EXISTS AUDITORIA (
                                         CODIGO_AUDITORIA    BIGSERIAL PRIMARY KEY,
                                         TABELA_AUDITADA     VARCHAR(100) NOT NULL,
    CODIGO_REGISTRO     BIGINT NOT NULL,
    OPERACAO            VARCHAR(20) NOT NULL CHECK (OPERACAO IN ('INSERT', 'UPDATE', 'DELETE')),
    CODIGO_USUARIO      BIGINT,  -- PODE SER NULL SE AÇÃO DO SISTEMA
    DATA_HORA_OPERACAO  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                      DADOS_ANTERIORES    JSONB,  -- NULL PARA INSERT
                                      DADOS_NOVOS         JSONB   -- NULL PARA DELETE
                                      );

-- ÍNDICES PARA CONSULTAS RÁPIDAS NA AUDITORIA
CREATE INDEX IDX_AUDITORIA_TABELA_REGISTRO ON AUDITORIA(TABELA_AUDITADA, CODIGO_REGISTRO);
CREATE INDEX IDX_AUDITORIA_USUARIO ON AUDITORIA(CODIGO_USUARIO);
CREATE INDEX IDX_AUDITORIA_DATA ON AUDITORIA(DATA_HORA_OPERACAO DESC);
CREATE INDEX IDX_AUDITORIA_OPERACAO ON AUDITORIA(OPERACAO);

COMMENT ON TABLE AUDITORIA IS
'TABELA CENTRAL DE AUDITORIA - REGISTRA TODAS AS OPERAÇÕES CRÍTICAS DO SISTEMA';

COMMENT ON COLUMN AUDITORIA.DADOS_ANTERIORES IS
'SNAPSHOT DO REGISTRO ANTES DA ALTERAÇÃO (JSON COMPLETO)';

COMMENT ON COLUMN AUDITORIA.DADOS_NOVOS IS
'SNAPSHOT DO REGISTRO DEPOIS DA ALTERAÇÃO (JSON COMPLETO)';

-- =====================================================
-- SEQUENCES PARA NUMERAÇÃO SEQUENCIAL
-- SERÃO USADAS PELAS FUNÇÕES DE GERAÇÃO DE NÚMEROS
-- =====================================================

-- SEQUENCE PARA CONTRATOS
CREATE SEQUENCE IF NOT EXISTS SEQ_NUMERO_CONTRATO START 1 INCREMENT 1;
COMMENT ON SEQUENCE SEQ_NUMERO_CONTRATO IS 'SEQUENCE PARA NUMERAÇÃO DE CONTRATOS (CT-2025-000001)';

-- SEQUENCE PARA ORDENS DE SERVIÇO
CREATE SEQUENCE IF NOT EXISTS SEQ_NUMERO_OS START 1 INCREMENT 1;
COMMENT ON SEQUENCE SEQ_NUMERO_OS IS 'SEQUENCE PARA NUMERAÇÃO DE OS (OS-2025-000001)';

-- SEQUENCE PARA FATURAS
CREATE SEQUENCE IF NOT EXISTS SEQ_NUMERO_FATURA START 1 INCREMENT 1;
COMMENT ON SEQUENCE SEQ_NUMERO_FATURA IS 'SEQUENCE PARA NUMERAÇÃO DE FATURAS (FAT-2025-000001)';

-- =====================================================
-- FIM DA MIGRATION V001
-- =====================================================