-- =====================================================
-- V003__CRIAR_TABELAS_CLIENTES.SQL
-- DESCRIÇÃO: ESTRUTURA COMPLETA DE CLIENTES (EMPRESAS B2B)
-- AUTOR: ERP PORTAL TEAM
-- DATA: 2025-01-10
-- =====================================================

-- =====================================================
-- TABELA: CLIENTES (EMPRESAS)
-- =====================================================
CREATE TABLE CLIENTES (
                          CODIGO_CLIENTE          BIGSERIAL PRIMARY KEY,

    -- DADOS CADASTRAIS
                          RAZAO_SOCIAL            VARCHAR(200) NOT NULL,
                          NOME_FANTASIA           VARCHAR(200),
                          CNPJ                    VARCHAR(18) UNIQUE NOT NULL,  -- FORMATO: 00.000.000/0000-00
                          INSCRICAO_ESTADUAL      VARCHAR(20),

    -- ENDEREÇO
                          CEP                     VARCHAR(10),
                          LOGRADOURO              VARCHAR(200),
                          NUMERO_ENDERECO         VARCHAR(20),
                          COMPLEMENTO             VARCHAR(100),
                          BAIRRO                  VARCHAR(100),
                          CIDADE                  VARCHAR(100),
                          ESTADO                  VARCHAR(2),  -- UF: SP, RJ, MG, ETC

    -- STATUS
                          STATUS_CLIENTE          VARCHAR(20) DEFAULT 'ATIVO' NOT NULL,

    -- AUDITORIA COMPLETA
                          CRIADO_EM               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CRIADO_POR              BIGINT NOT NULL,
                          ATUALIZADO_EM           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          ATUALIZADO_POR          BIGINT NOT NULL,
                          EXCLUIDO_EM             TIMESTAMP WITH TIME ZONE,
                          EXCLUIDO_POR            BIGINT,

    -- FOREIGN KEYS
                          CONSTRAINT FK_CLIENTES_CRIADO_POR
                              FOREIGN KEY (CRIADO_POR)
                                  REFERENCES USUARIOS(CODIGO_USUARIO)
                                  ON DELETE RESTRICT,

                          CONSTRAINT FK_CLIENTES_ATUALIZADO_POR
                              FOREIGN KEY (ATUALIZADO_POR)
                                  REFERENCES USUARIOS(CODIGO_USUARIO)
                                  ON DELETE RESTRICT,

                          CONSTRAINT FK_CLIENTES_EXCLUIDO_POR
                              FOREIGN KEY (EXCLUIDO_POR)
                                  REFERENCES USUARIOS(CODIGO_USUARIO)
                                  ON DELETE SET NULL,

    -- CONSTRAINTS DE VALIDAÇÃO
                          CONSTRAINT CHK_CLIENTE_STATUS CHECK (
                              STATUS_CLIENTE IN ('ATIVO', 'SUSPENSO', 'ENCERRADO')
                              ),

                          CONSTRAINT CHK_CLIENTE_ESTADO CHECK (
                              ESTADO IS NULL OR LENGTH(ESTADO) = 2
                              ),

                          CONSTRAINT CHK_CLIENTE_CNPJ_FORMATO CHECK (
                              CNPJ ~ '^\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}$'  -- VALIDA FORMATO
),

    CONSTRAINT CHK_CLIENTE_RAZAO_SOCIAL_MINIMO CHECK (
        LENGTH(TRIM(RAZAO_SOCIAL)) >= 3
    ),

    CONSTRAINT CHK_CLIENTE_EXCLUIDO_LOGICA CHECK (
        (EXCLUIDO_EM IS NULL AND EXCLUIDO_POR IS NULL) OR
        (EXCLUIDO_EM IS NOT NULL AND EXCLUIDO_POR IS NOT NULL)
    )
);

-- =====================================================
-- ÍNDICES ESTRATÉGICOS - CLIENTES
-- =====================================================

-- ÍNDICE UNIQUE PARCIAL: CNPJ ÚNICO APENAS ENTRE CLIENTES ATIVOS
CREATE UNIQUE INDEX IDX_CLIENTES_CNPJ_ATIVO
    ON CLIENTES(CNPJ)
    WHERE EXCLUIDO_EM IS NULL;

-- ÍNDICES PARA FILTROS COMUNS
CREATE INDEX IDX_CLIENTES_STATUS ON CLIENTES(STATUS_CLIENTE);
CREATE INDEX IDX_CLIENTES_CIDADE_ESTADO ON CLIENTES(CIDADE, ESTADO);
CREATE INDEX IDX_CLIENTES_CRIADO_EM ON CLIENTES(CRIADO_EM DESC);
CREATE INDEX IDX_CLIENTES_EXCLUIDO ON CLIENTES(EXCLUIDO_EM) WHERE EXCLUIDO_EM IS NOT NULL;

-- ÍNDICE PARA BUSCA TEXTUAL (NOME/RAZÃO SOCIAL)
CREATE INDEX IDX_CLIENTES_RAZAO_SOCIAL_LOWER ON CLIENTES(LOWER(RAZAO_SOCIAL));
CREATE INDEX IDX_CLIENTES_NOME_FANTASIA_LOWER ON CLIENTES(LOWER(NOME_FANTASIA)) WHERE NOME_FANTASIA IS NOT NULL;

-- ÍNDICE COMPOSTO PARA LISTAGEM PADRÃO (STATUS + NOME)
CREATE INDEX IDX_CLIENTES_LISTAGEM ON CLIENTES(STATUS_CLIENTE, RAZAO_SOCIAL);

-- ÍNDICE PARA AUDITORIA (QUEM CRIOU/ATUALIZOU)
CREATE INDEX IDX_CLIENTES_AUDITORIA ON CLIENTES(CRIADO_POR, ATUALIZADO_POR);

-- =====================================================
-- COMENTÁRIOS - CLIENTES
-- =====================================================
COMMENT ON TABLE CLIENTES IS
'CADASTRO DE EMPRESAS CLIENTES (B2B) DA SOFTWARE HOUSE';

COMMENT ON COLUMN CLIENTES.STATUS_CLIENTE IS
'ATIVO: OPERANDO NORMALMENTE | SUSPENSO: TEMPORARIAMENTE INATIVO (SEM NOVOS CONTRATOS) | ENCERRADO: RELAÇÃO COMERCIAL FINALIZADA';

COMMENT ON COLUMN CLIENTES.CNPJ IS
'CNPJ FORMATADO (00.000.000/0000-00). ÚNICO ENTRE CLIENTES ATIVOS.';

COMMENT ON COLUMN CLIENTES.EXCLUIDO_EM IS
'SOFT DELETE: DATA/HORA DA EXCLUSÃO. NULL = REGISTRO ATIVO';

-- =====================================================
-- TABELA: CONTATOS DO CLIENTE
-- =====================================================
CREATE TABLE CONTATOS_CLIENTE (
                                  CODIGO_CONTATO          BIGSERIAL PRIMARY KEY,
                                  CODIGO_CLIENTE          BIGINT NOT NULL,

    -- DADOS DO CONTATO
                                  NOME_CONTATO            VARCHAR(100) NOT NULL,
                                  EMAIL                   VARCHAR(100),
                                  TELEFONE                VARCHAR(20),
                                  CELULAR                 VARCHAR(20),
                                  CARGO                   VARCHAR(100),

    -- FLAGS
                                  PRINCIPAL               BOOLEAN DEFAULT FALSE NOT NULL,
                                  ATIVO                   BOOLEAN DEFAULT TRUE NOT NULL,

    -- AUDITORIA BÁSICA
                                  CRIADO_EM               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  ATUALIZADO_EM           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- FOREIGN KEYS
                                  CONSTRAINT FK_CONTATOS_CLIENTE
                                      FOREIGN KEY (CODIGO_CLIENTE)
                                          REFERENCES CLIENTES(CODIGO_CLIENTE)
                                          ON DELETE CASCADE,  -- SE CLIENTE É EXCLUÍDO, CONTATOS TAMBÉM SÃO

    -- CONSTRAINTS
                                  CONSTRAINT CHK_CONTATO_NOME_MINIMO CHECK (
                                      LENGTH(TRIM(NOME_CONTATO)) >= 3
                                      ),

                                  CONSTRAINT CHK_CONTATO_EMAIL_FORMATO CHECK (
                                      EMAIL IS NULL OR
                                      EMAIL ~* '^[A-ZA-Z0-9._%+-]+@[A-ZA-Z0-9.-]+\.[A-ZA-Z]{2,}$'
),

    CONSTRAINT CHK_CONTATO_PELO_MENOS_UM_MEIO CHECK (
        EMAIL IS NOT NULL OR TELEFONE IS NOT NULL OR CELULAR IS NOT NULL
    )
);

-- =====================================================
-- ÍNDICES - CONTATOS CLIENTE
-- =====================================================
CREATE INDEX IDX_CONTATOS_CLIENTE ON CONTATOS_CLIENTE(CODIGO_CLIENTE);
CREATE INDEX IDX_CONTATOS_PRINCIPAL ON CONTATOS_CLIENTE(CODIGO_CLIENTE, PRINCIPAL) WHERE PRINCIPAL = TRUE;
CREATE INDEX IDX_CONTATOS_ATIVO ON CONTATOS_CLIENTE(ATIVO) WHERE ATIVO = TRUE;
CREATE INDEX IDX_CONTATOS_EMAIL ON CONTATOS_CLIENTE(LOWER(EMAIL)) WHERE EMAIL IS NOT NULL;

-- ÍNDICE PARCIAL: APENAS CONTATOS ATIVOS E PRINCIPAIS
CREATE INDEX IDX_CONTATOS_ATIVOS_PRINCIPAIS
    ON CONTATOS_CLIENTE(CODIGO_CLIENTE)
    WHERE ATIVO = TRUE AND PRINCIPAL = TRUE;

-- =====================================================
-- COMENTÁRIOS - CONTATOS
-- =====================================================
COMMENT ON TABLE CONTATOS_CLIENTE IS
'PESSOAS DE CONTATO NAS EMPRESAS CLIENTES (PODE HAVER MÚLTIPLOS CONTATOS POR CLIENTE)';

COMMENT ON COLUMN CONTATOS_CLIENTE.PRINCIPAL IS
'INDICA O CONTATO PRINCIPAL DO CLIENTE. APENAS UM CONTATO POR CLIENTE DEVE SER PRINCIPAL.';

COMMENT ON COLUMN CONTATOS_CLIENTE.ATIVO IS
'PERMITE DESATIVAR CONTATO SEM EXCLUIR (PESSOA SAIU DA EMPRESA, ETC)';

-- =====================================================
-- TABELA: OBSERVAÇÕES INTERNAS SOBRE CLIENTES
-- =====================================================
CREATE TABLE OBSERVACOES_CLIENTE (
                                     CODIGO_OBSERVACAO           BIGSERIAL PRIMARY KEY,
                                     CODIGO_CLIENTE              BIGINT NOT NULL,
                                     CODIGO_USUARIO              BIGINT NOT NULL,

    -- CONTEÚDO
                                     OBSERVACAO                  TEXT NOT NULL,

    -- METADATA
                                     DATA_HORA_OBSERVACAO        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- FOREIGN KEYS
                                     CONSTRAINT FK_OBSERVACOES_CLIENTE
                                         FOREIGN KEY (CODIGO_CLIENTE)
                                             REFERENCES CLIENTES(CODIGO_CLIENTE)
                                             ON DELETE CASCADE,

                                     CONSTRAINT FK_OBSERVACOES_USUARIO
                                         FOREIGN KEY (CODIGO_USUARIO)
                                             REFERENCES USUARIOS(CODIGO_USUARIO)
                                             ON DELETE RESTRICT,

    -- CONSTRAINTS
                                     CONSTRAINT CHK_OBSERVACAO_MINIMO CHECK (
                                         LENGTH(TRIM(OBSERVACAO)) >= 5
                                         )
);

-- =====================================================
-- ÍNDICES - OBSERVAÇÕES
-- =====================================================
CREATE INDEX IDX_OBSERVACOES_CLIENTE ON OBSERVACOES_CLIENTE(CODIGO_CLIENTE, DATA_HORA_OBSERVACAO DESC);
CREATE INDEX IDX_OBSERVACOES_USUARIO ON OBSERVACOES_CLIENTE(CODIGO_USUARIO);
CREATE INDEX IDX_OBSERVACOES_DATA ON OBSERVACOES_CLIENTE(DATA_HORA_OBSERVACAO DESC);

COMMENT ON TABLE OBSERVACOES_CLIENTE IS
'NOTAS INTERNAS SOBRE CLIENTES (NÃO VISÍVEIS AO CLIENTE). ÚTIL PARA REGISTRAR HISTÓRICO DE INTERAÇÕES.';

-- =====================================================
-- TRIGGERS: ATUALIZAÇÃO AUTOMÁTICA DE TIMESTAMPS
-- =====================================================
CREATE TRIGGER TRG_CLIENTES_ATUALIZAR_TIMESTAMP
    BEFORE UPDATE ON CLIENTES
    FOR EACH ROW
    EXECUTE FUNCTION ATUALIZAR_TIMESTAMP_ATUALIZACAO();

CREATE TRIGGER TRG_CONTATOS_ATUALIZAR_TIMESTAMP
    BEFORE UPDATE ON CONTATOS_CLIENTE
    FOR EACH ROW
    EXECUTE FUNCTION ATUALIZAR_TIMESTAMP_ATUALIZACAO();

-- =====================================================
-- TRIGGER: GARANTIR APENAS UM CONTATO PRINCIPAL POR CLIENTE
-- =====================================================
CREATE OR REPLACE FUNCTION VALIDAR_CONTATO_PRINCIPAL()
RETURNS TRIGGER AS $$
BEGIN
    -- SE ESTÁ MARCANDO COMO PRINCIPAL
    IF NEW.PRINCIPAL = TRUE THEN
        -- DESMARCA OUTROS CONTATOS PRINCIPAIS DO MESMO CLIENTE
UPDATE CONTATOS_CLIENTE
SET PRINCIPAL = FALSE
WHERE CODIGO_CLIENTE = NEW.CODIGO_CLIENTE
  AND CODIGO_CONTATO != COALESCE(NEW.CODIGO_CONTATO, 0)
          AND PRINCIPAL = TRUE;
END IF;

RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_CONTATOS_VALIDAR_PRINCIPAL
    BEFORE INSERT OR UPDATE ON CONTATOS_CLIENTE
                         FOR EACH ROW
                         EXECUTE FUNCTION VALIDAR_CONTATO_PRINCIPAL();

COMMENT ON FUNCTION VALIDAR_CONTATO_PRINCIPAL() IS
'GARANTE QUE APENAS UM CONTATO SEJA MARCADO COMO PRINCIPAL POR CLIENTE';

-- =====================================================
-- TRIGGER: VALIDAR CNPJ ANTES DE INSERIR/ATUALIZAR
-- =====================================================
CREATE OR REPLACE FUNCTION VALIDAR_CNPJ_CLIENTE()
RETURNS TRIGGER AS $$
BEGIN
    -- REMOVE FORMATAÇÃO DO CNPJ
    NEW.CNPJ := REGEXP_REPLACE(NEW.CNPJ, '[^0-9]', '', 'G');

    -- VALIDA FORMATO BÁSICO
    IF NOT VALIDAR_FORMATO_CNPJ(NEW.CNPJ) THEN
        RAISE EXCEPTION 'CNPJ INVÁLIDO: %', NEW.CNPJ;
END IF;

    -- REFORMATA COM PONTUAÇÃO
    NEW.CNPJ := FORMATAR_CNPJ(NEW.CNPJ);

RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_CLIENTES_VALIDAR_CNPJ
    BEFORE INSERT OR UPDATE ON CLIENTES
                         FOR EACH ROW
                         EXECUTE FUNCTION VALIDAR_CNPJ_CLIENTE();

COMMENT ON FUNCTION VALIDAR_CNPJ_CLIENTE() IS
'VALIDA E FORMATA CNPJ AUTOMATICAMENTE ANTES DE SALVAR';

-- =====================================================
-- TRIGGER: IMPEDIR EXCLUSÃO FÍSICA DE CLIENTES COM RELACIONAMENTOS
-- =====================================================
CREATE OR REPLACE FUNCTION IMPEDIR_EXCLUSAO_CLIENTE_COM_RELACIONAMENTOS()
RETURNS TRIGGER AS $$
DECLARE
TEM_CONTRATOS INTEGER;
    TEM_OS INTEGER;
BEGIN
    -- VERIFICA SE HÁ CONTRATOS
SELECT COUNT(*) INTO TEM_CONTRATOS
FROM CONTRATOS
WHERE CODIGO_CLIENTE = OLD.CODIGO_CLIENTE;

-- VERIFICA SE HÁ OS
SELECT COUNT(*) INTO TEM_OS
FROM ORDENS_SERVICO
WHERE CODIGO_CLIENTE = OLD.CODIGO_CLIENTE;

-- SE TIVER RELACIONAMENTOS, IMPEDE EXCLUSÃO FÍSICA
IF TEM_CONTRATOS > 0 OR TEM_OS > 0 THEN
        RAISE EXCEPTION 'CLIENTE POSSUI % CONTRATOS E % ORDENS DE SERVIÇO. USE EXCLUSÃO LÓGICA (SOFT DELETE).',
            TEM_CONTRATOS, TEM_OS;
END IF;

RETURN OLD;
END;
$$ LANGUAGE PLPGSQL;

-- NOTA: ESTE TRIGGER SERÁ ATIVADO APENAS NA EXCLUSÃO FÍSICA (DELETE).
-- O SOFT DELETE (UPDATE COM EXCLUIDO_EM) NÃO DISPARA ESTE TRIGGER.
CREATE TRIGGER TRG_CLIENTES_IMPEDIR_EXCLUSAO
    BEFORE DELETE ON CLIENTES
    FOR EACH ROW
    EXECUTE FUNCTION IMPEDIR_EXCLUSAO_CLIENTE_COM_RELACIONAMENTOS();

COMMENT ON FUNCTION IMPEDIR_EXCLUSAO_CLIENTE_COM_RELACIONAMENTOS() IS
'IMPEDE EXCLUSÃO FÍSICA DE CLIENTES QUE POSSUEM CONTRATOS OU OS. FORÇA USO DE SOFT DELETE.';

-- =====================================================
-- VIEWS ÚTEIS
-- =====================================================

-- VIEW: CLIENTES ATIVOS COM CONTATO PRINCIPAL
CREATE OR REPLACE VIEW VW_CLIENTES_ATIVOS_COM_CONTATO AS
SELECT
    C.CODIGO_CLIENTE,
    C.RAZAO_SOCIAL,
    C.NOME_FANTASIA,
    C.CNPJ,
    C.CIDADE,
    C.ESTADO,
    C.STATUS_CLIENTE,
    CC.NOME_CONTATO AS CONTATO_PRINCIPAL_NOME,
    CC.EMAIL AS CONTATO_PRINCIPAL_EMAIL,
    CC.TELEFONE AS CONTATO_PRINCIPAL_TELEFONE,
    C.CRIADO_EM
FROM CLIENTES C
         LEFT JOIN CONTATOS_CLIENTE CC ON C.CODIGO_CLIENTE = CC.CODIGO_CLIENTE AND CC.PRINCIPAL = TRUE
WHERE C.EXCLUIDO_EM IS NULL
ORDER BY C.RAZAO_SOCIAL;

COMMENT ON VIEW VW_CLIENTES_ATIVOS_COM_CONTATO IS
'VISÃO SIMPLIFICADA DE CLIENTES ATIVOS COM SEUS CONTATOS PRINCIPAIS (PARA LISTAGENS)';

-- =====================================================
-- FIM DA MIGRATION V003
-- =====================================================